# Generated by Django 3.2 on 2021-04-12 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pts_pops_app', '0002_auto_20210412_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pts_pops_app.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_bio',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_email',
            field=models.EmailField(default='Testing@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
