# Generated by Django 3.2 on 2021-04-14 14:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pts_pops_app', '0003_auto_20210412_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinions', models.TextField()),
                ('good', models.CharField(choices=[('1', "It was okay but you could've done better Justin if you did not play videogames"), ('2', 'It was really decent for a 3 days worth of code'), ('3', 'Nice! This was unexpected!')], max_length=100)),
                ('name', models.CharField(blank=True, help_text='This is not required!!!', max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(default=django.contrib.auth.models.AnonymousUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner_profile',
            field=models.ForeignKey(default=django.contrib.auth.models.AnonymousUser, on_delete=django.db.models.deletion.CASCADE, to='pts_pops_app.profile'),
        ),
    ]
