# Generated by Django 3.2 on 2021-04-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_pops_app', '0003_auto_20210412_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, default=None, upload_to='uploaded_img/')),
            ],
        ),
    ]
