# Generated by Django 3.2 on 2021-04-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_pops_app', '0005_auto_20210414_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to='https://pts-popcorn.s3.amazonaws.com/uploaded_img/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_photo',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='https://pts-popcorn.s3.amazonaws.com/user_profile_pictures/'),
        ),
    ]
