# Generated by Django 3.2 on 2021-04-18 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pts_pops_app', '0008_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='https://pts-popcorn.s3.amazonaws.com/choice_img/'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
